### ISSUE TITLE
Estructura

### ISSUE THREAD

**Issue by harumi-matias** [gustavolsjsa/Equipo01#7]
Hola @Valantara veo que subiste los archivos directo en la raíz, debes colocar cada tipo de archivo en su carpera ej. imagenes en images, css en la carpeta de css y así.

**Comment by gustavolsjsa** [comment]
Hola Val y Harumi 

Oigan uno de los estilos de la carga que hizo Val hace rato conflictúa con lo que ya tenía y me esta moviendo varias cosas. 
es este:

* {
	margin: 0px 0px;
	font-family: 'Montserrat', sans-serif;
}

El problema es que con el asterisco se aplican esos estilos a todos los elementos html, lo desactivé y parece que no afecta al index,  al menos yo lo veo igual, pero en mi sección se solucionó el problema. A ver cómo lo ven ustedes.

Saludos

**Comment by harumi-matias** [comment]
Por mi esta bien que lo quites, creo que no me afecta en mis estilos.
